logging:
  appenders:
    - type: file
      currentLogFilename: billing.log
      archivedLogFilenamePattern: billing-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "~billing[${PID:- }]: %d{yyyy-MM-dd'T'HH:mm:ss.SSSZ};%t;%mdc{X-CorrelationId:--};%level;%logger;%m%n"
    - type: console
      logFormat: "~billing[${PID:- }]: %d{yyyy-MM-dd'T'HH:mm:ss.SSSZ};%t;%mdc{X-CorrelationId:--};%level;%logger;%m%n"

database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/billing
  user: billing
  password: billing
